// Snowman v1.9: Learn to Readle's reviewed answers.js is the single source of secret words.
// This file stores only Snowman-specific clue overrides and adapts the shared word bank.
(() => {
  'use strict';

  const clueOverrides = {
    'ALSO': 'Another way to say too',
    'AMID': 'In the middle of',
    'BEEN': 'A form of the word be',
    'BERG': 'A large piece of floating ice',
    'CAME': 'Moved toward this place',
    'CASE': 'A container or a situation',
    'COME': 'Move toward this place',
    'DEAR': 'Loved or special to you',
    'DIED': 'Stopped being alive',
    'DOES': 'A form of the word do',
    'DONE': 'Finished',
    'DREW': 'Made a picture with a pencil',
    'DUTY': 'A job you are responsible for',
    'ELSE': 'Another choice or something different',
    'EVEN': 'Flat, equal, or divisible by two',
    'EVER': 'At any time',
    'FACT': 'Something that is true',
    'FATE': 'What is supposed to happen',
    'FEAR': 'The feeling of being scared',
    'FEEL': 'To notice with touch or emotion',
    'FELL': 'Dropped down',
    'FELT': 'Noticed by touch or emotion',
    'FIRM': 'Strong and not soft',
    'FORM': 'A shape or a paper to fill out',
    'FROM': 'Starting at a place or person',
    'FULL': 'Holding as much as possible',
    'GAVE': 'Handed something to someone',
    'GONE': 'No longer here',
    'GREW': 'Got bigger or older',
    'HAVE': 'To own or hold something',
    'HELD': 'Kept in your hand',
    'HERE': 'In this place',
    'HOLD': 'Keep something in your hand',
    'INTO': 'Moving to the inside of',
    'JUST': 'Fair, exact, or only a moment ago',
    'KEPT': 'Held onto or saved',
    'KNEW': 'Already understood something',
    'KNOW': 'To understand or be aware of',
    'LAID': 'Put something down',
    'LEAD': 'To guide the way',
    'LESS': 'A smaller amount',
    'LIKE': 'To enjoy something or be similar',
    'LIMB': 'An arm, leg, or large tree branch',
    'LORD': 'A title for an important ruler',
    'LOSS': 'When something is no longer yours',
    'LOST': 'Unable to find the way or something missing',
    'MADE': 'Created or built',
    'MAID': 'A person who helps clean a home',
    'MASS': 'A large amount or how much matter something has',
    'MEAN': 'To intend or to stand for something',
    'MOST': 'The greatest amount',
    'MUCH': 'A large amount',
    'MUST': 'Something you have to do',
    'NONE': 'Not even one',
    'ONCE': 'One time',
    'ONLY': 'No others besides this one',
    'PAID': 'Gave money for something',
    'PAIN': 'A hurt feeling in your body',
    'PALE': 'Light in color',
    'PASS': 'Go by or hand something along',
    'PAST': 'A time that already happened',
    'RAYS': 'Lines of light from the sun',
    'REAL': 'Actually true or existing',
    'RICH': 'Having lots of money or a strong flavor',
    'RISE': 'Move upward',
    'RODE': 'Traveled on a bike, horse, or vehicle',
    'SAID': 'Spoke some words',
    'SAKE': 'For the purpose or benefit of something',
    'SAME': 'Not different',
    'SAVE': 'Keep safe or keep for later',
    'SCAR': 'A mark left after a cut heals',
    'SEEM': 'To appear to be',
    'SEEN': 'Already looked at',
    'SELF': 'Your own person',
    'SENT': 'Made something go to another place',
    'SHOT': 'A quick try, a photograph, or something fired',
    'SOME': 'A certain amount but not all',
    'SORT': 'A kind or type',
    'SOUL': 'The inner spirit of a person',
    'SUCH': 'Of that kind',
    'SURE': 'Certain or confident',
    'TERM': 'A word, a period of time, or a school session',
    'THAN': 'Used when comparing two things',
    'THAT': 'Points to a certain thing',
    'THEM': 'A word for those people or things',
    'THEN': 'At that time or next',
    'THEY': 'A word for a group of people or things',
    'THIS': 'Points to something nearby',
    'THUS': 'Another way to say therefore',
    'TILL': 'Until a certain time',
    'TOLD': 'Gave someone information',
    'TOOK': 'Picked up or carried away',
    'TYPE': 'A kind of thing or to write with keys',
    'UPON': 'On top of or right after',
    'USED': 'Already put to work',
    'VEIN': 'A tube that carries blood toward the heart',
    'VERY': 'A word that makes a description stronger',
    'VOTE': 'Choose by marking your choice',
    'WENT': 'Moved from one place to another',
    'WERE': 'A past form of the word be',
    'WHAT': 'A question word asking which thing',
    'WHEN': 'A question word asking what time',
    'WHOM': 'A word asking which person receives an action',
    'WIFE': 'A married woman',
    'WILL': 'A word about the future or determination',
    'WITH': 'Together or accompanied by',
    'YOUR': 'Belonging to you',
    'ABOUT': 'Concerning something or nearby',
    'ABOVE': 'Higher than something else',
    'ACUTE': 'Sharp, severe, or less than a right angle',
    'AFTER': 'Later than something else',
    'AGAIN': 'One more time',
    'AGREE': 'To have the same opinion',
    'ALIVE': 'Living, not dead',
    'ALLOW': 'To let something happen',
    'ALONE': 'By yourself',
    'ALONG': 'Moving beside or forward with',
    'AMONG': 'In the middle of a group',
    'ANGRY': 'Feeling mad',
    'APART': 'Separated from each other',
    'ASIDE': 'To one side',
    'AVOID': 'Keep away from something',
    'BEGAN': 'Started',
    'BEGIN': 'To start',
    'BEGUN': 'Already started',
    'BEING': 'Existing or living',
    'BELOW': 'Lower than something else',
    'BLACK': 'The darkest color',
    'BLAME': 'Say someone caused a problem',
    'BLOOD': 'Red liquid that moves through your body',
    'BOOTS': 'Shoes that cover the ankle or more',
    'BOUND': 'Tied, headed somewhere, or certain',
    'BREAK': 'To crack, stop, or take a rest',
    'BRING': 'Carry something to this place',
    'BROAD': 'Wide from side to side',
    'BROKE': 'Cracked or had no money',
    'BROWN': 'A color like chocolate or tree bark',
    'BRUSH': 'A tool with bristles or to sweep lightly',
    'BUILT': 'Made by putting parts together',
    'BURST': 'Break open suddenly',
    'CANAL': 'A man-made waterway',
    'CARRY': 'Hold and move something',
    'CARTS': 'Small vehicles used to carry things',
    'CAUSE': 'Something that makes another thing happen',
    'CHAIR': 'A seat for one person',
    'CHEST': 'The front part of your body below your neck',
    'CHIEF': 'The leader or most important person',
    'CHILD': 'A young person',
    'CIVIL': 'Polite or related to citizens',
    'CLASS': 'A group of students learning together',
    'CLEAR': 'Easy to see through or understand',
    'CLOCK': 'Something that tells the time',
    'CLOSE': 'Nearby or to shut something',
    'COULD': 'A word meaning was able to or might',
    'COUNT': 'Say numbers in order or find how many',
    'COURT': 'A place for law or some sports',
    'CRIED': 'Made tears or called out loudly',
    'CROSS': 'Go from one side to another',
    'CROWD': 'A large group of people together',
    'DOING': 'Working on or performing something',
    'DOUBT': 'A feeling of not being sure',
    'DRAWN': 'Made as a picture or pulled',
    'DREAM': 'A story in your mind while sleeping',
    'DRESS': 'Clothing or to put clothes on',
    'DRINK': 'A liquid you swallow',
    'DRIVE': 'Control a car or push something forward',
    'DROVE': 'Controlled a car in the past',
    'EARLY': 'Before the usual time',
    'EDGES': 'The outside borders of things',
    'EIGHT': 'The number after seven',
    'ELBOW': 'The joint in the middle of your arm',
    'ENEMY': 'Someone on the opposite side',
    'ENTER': 'Go inside',
    'EQUAL': 'The same amount or value',
    'EVENT': 'Something that happens',
    'EVERY': 'Each one in a group',
    'FAVOR': 'A kind act or something you prefer',
    'FEVER': 'A body temperature higher than normal',
    'FIELD': 'An open area of land',
    'FIFTY': 'The number 50',
    'FIGHT': 'A struggle or argument',
    'FIRST': 'Before all the others',
    'FIXED': 'Repaired or made not to move',
    'FLAME': 'The glowing part of a fire',
    'FLANK': 'The side of a person, animal, or group',
    'FLOOR': 'The surface you walk on inside',
    'FLUID': 'A liquid or something that flows',
    'FORCE': 'A push or pull',
    'FORTH': 'Forward or outward',
    'FORTY': 'The number 40',
    'FOUND': 'Discovered or located',
    'FRESH': 'New, clean, or recently made',
    'FRONT': 'The forward-facing side',
    'GIVEN': 'Handed or provided',
    'GLASS': 'A clear material used in windows',
    'GOING': 'Moving or traveling somewhere',
    'GRAND': 'Large, impressive, or one thousand',
    'GRASS': 'Green plants that cover many lawns',
    'GREAT': 'Very good or very large',
    'GREEN': 'A color like leaves and grass',
    'GROUP': 'A number of things together',
    'GROWN': 'Become bigger or older',
    'HAPPY': 'Feeling glad or joyful',
    'HEARD': 'Received a sound with your ears',
    'HEART': 'The organ that pumps blood',
    'HEAVY': 'Weighing a lot',
    'HONOR': 'Respect and praise',
    'HOUSE': 'A building where people live',
    'HUMAN': 'A person',
    'BEAR': 'A large furry animal',
    'BIRD': 'An animal with feathers',
    'BOOK': 'Something you read',
    'CAKE': 'A sweet birthday treat',
    'CAMP': 'Sleep outside in a tent',
    'DUCK': 'A bird that likes water',
    'FISH': 'An animal that swims',
    'FROG': 'A green animal that hops',
    'GAME': 'Something you play',
    'GOAT': 'A farm animal',
    'KITE': 'You fly it in the wind',
    'LION': 'A big cat with a mane',
    'MOON': 'You can see it at night',
    'RAIN': 'Water that falls from clouds',
    'SHIP': 'A large boat',
    'SHOE': 'You wear it on your foot',
    'STAR': 'It twinkles in the night sky',
    'TREE': 'A tall plant with a trunk',
    'WAVE': 'Moving water at the beach',
    'WOLF': 'A wild animal related to dogs',
    'APPLE': 'A crunchy fruit',
    'BEACH': 'A sandy place by the water',
    'BREAD': 'You might use it for a sandwich',
    'CLOUD': 'A fluffy shape in the sky',
    'DANCE': 'Move your body to music',
    'EARTH': 'The planet we live on',
    'GRAPE': 'A small round fruit',
    'HORSE': 'An animal people can ride',
    'JUICE': 'A fruity drink',
    'MOUSE': 'A small animal with a long tail',
    'NIGHT': 'The time when it is dark',
    'OCEAN': 'A huge body of salt water',
    'PANDA': 'A black-and-white bear',
    'PIZZA': 'A cheesy food cut into slices',
    'PLANT': 'A living thing that grows',
    'ROBOT': 'A machine that can do tasks',
    'SHEEP': 'A farm animal with wool',
    'SMILE': 'What your face does when you are happy',
    'TRAIN': 'A vehicle that travels on tracks',
    'WHALE': 'A very large ocean animal',
    'ANIMAL': 'A living creature',
    'BANANA': 'A long yellow fruit',
    'BUBBLE': 'A round pocket of air in soapy water',
    'CASTLE': 'A large home for kings and queens',
    'COOKIE': 'A small sweet baked treat',
    'DRAGON': 'A make-believe fire-breathing creature',
    'FLOWER': 'A colorful part of a plant',
    'FOREST': 'A place with many trees',
    'GARDEN': 'A place where plants are grown',
    'KITTEN': 'A baby cat',
    'MONKEY': 'An animal that can climb and swing',
    'ORANGE': 'A fruit and a color',
    'PENCIL': 'You use it to write or draw',
    'PUPPET': 'A toy you can make move',
    'RABBIT': 'An animal with long ears',
    'ROCKET': 'A vehicle that can travel to space',
    'SCHOOL': 'A place where children learn',
    'SPIDER': 'A creature with eight legs',
    'TURTLE': 'An animal with a shell',
    'WINTER': 'The coldest season',
    'BALLOON': 'A colorful object filled with air',
    'BEDROOM': 'A room where you sleep',
    'CHICKEN': 'A farm bird',
    'DOLPHIN': 'A smart ocean animal',
    'DRAWING': 'A picture made with a pencil or crayon',
    'FIREMAN': 'A person who helps put out fires',
    'GIRAFFE': 'A very tall animal with a long neck',
    'HAMSTER': 'A small furry pet',
    'KITCHEN': 'A room where food is prepared',
    'LADYBUG': 'A small red beetle with spots',
    'LIBRARY': 'A place full of books',
    'PENGUIN': 'A black-and-white bird that cannot fly',
    'RAINBOW': 'Colors that can appear after rain',
    'SANDBOX': 'A box where kids can play with sand',
    'SNOWMAN': 'A person-shaped figure made of snow',
    'SUNSHINE': 'Bright light from the sun',
    'TRICYCLE': 'A three-wheeled ride',
    'VOLCANO': 'A mountain that can erupt',
    'PANCAKE': 'A round breakfast food cooked on a griddle',
    'POPCORN': 'A crunchy snack made from corn',
    'AIRPLANE': 'A vehicle that flies in the sky',
    'BASEBALL': 'A sport played with a bat and ball',
    'BIRTHDAY': 'The day you celebrate getting one year older',
    'DINOSAUR': 'An ancient animal that lived long ago',
    'ELEPHANT': 'A huge animal with a trunk',
    'FOOTBALL': 'A sport played with an oval ball',
    'KANGAROO': 'An animal that hops and has a pouch',
    'MOUNTAIN': 'Very high land',
    'NOTEBOOK': 'A book of blank pages for writing',
    'PLAYROOM': 'A room for toys and games',
    'SANDWICH': 'Food between slices of bread',
    'SEAHORSE': 'A tiny ocean animal shaped a bit like a horse',
    'SNOWBALL': 'A ball made of packed snow',
    'SQUIRREL': 'A furry animal that likes nuts',
    'SUNLIGHT': 'Light that comes from the sun',
    'TREASURE': 'Something valuable that might be hidden',
    'UMBRELLA': 'You hold it over your head in the rain',
    'VACATION': 'Time away from school or work',
    'RAINCOAT': 'A coat worn in wet weather',

    // Clue bank expansion — first broad pass across common 4-letter words.
    'ABLE': 'Can do something',
    'AREA': 'A place or part of a place',
    'ARMY': 'A large group of soldiers',
    'AWAY': 'Not here',
    'BABY': 'A very young child',
    'BACK': 'The part of your body behind you',
    'BALL': 'A round thing used in many games',
    'BANK': 'A place that keeps money safe',
    'BENT': 'Not straight',
    'BEST': 'Better than all the rest',
    'BILL': 'Money you owe, or a paper dollar',
    'BLUE': 'The color of a clear sky',
    'BOAT': 'A vehicle that travels on water',
    'BODY': 'All of a person or animal',
    'BONE': 'A hard part inside your body',
    'BOTH': 'The two of them together',
    'CALL': 'Talk to someone by phone',
    'CALM': 'Peaceful and not upset',
    'CARD': 'A small piece of stiff paper',
    'CARE': 'Look after someone or something',
    'CITY': 'A large town with many people',
    'COAT': 'Warm clothing worn over your clothes',
    'COLD': 'The opposite of hot',
    'CORN': 'A yellow vegetable that grows on a cob',
    'CRAB': 'An ocean animal with claws',
    'DARK': 'With little or no light',
    'DEEP': 'Going far down',
    'DEER': 'A wild animal that may have antlers',
    'DESK': 'A table used for schoolwork or work',
    'DOOR': 'You open it to enter a room',
    'DOWN': 'The opposite of up',
    'EACH': 'Every one by itself',
    'EAST': 'The direction where the sun rises',
    'EASY': 'Not hard to do',
    'FACE': 'The front of your head',
    'FALL': 'To drop down, or a season of the year',
    'FARM': 'A place where crops or animals are raised',
    'FEET': 'You stand and walk on them',
    'FIND': 'To discover where something is',
    'FINE': 'Okay or doing well',
    'FIRE': 'Hot flames that give heat and light',
    'FIVE': 'The number after four',
    'FLAG': 'A piece of cloth that can represent a place',
    'FOOT': 'The body part at the end of your leg',
    'FOUR': 'The number after three',
    'FREE': 'Not trapped or not costing money',
    'GIRL': 'A young female person',
    'GIVE': 'To hand something to someone else',
    'GLAD': 'Happy about something',
    'GOLD': 'A shiny yellow metal',
    'GOOD': 'Nice, right, or well done',
    'GRAY': 'A color between black and white',
    'HAIR': 'It grows on your head',
    'HALF': 'One of two equal parts',
    'HAND': 'The body part with fingers',
    'HARD': 'Not easy, or not soft',
    'HEAD': 'The top part of your body',
    'HEAR': 'To notice sound with your ears',
    'HELP': 'To make something easier for someone',
    'HIGH': 'Far above the ground',
    'HILL': 'Raised land smaller than a mountain',
    'HOME': 'The place where you live',
    'HOPE': 'To wish for something good to happen',
    'HOUR': 'Sixty minutes',
    'HUGE': 'Very, very big',
    'IDEA': 'A thought or plan in your mind',
    'JUMP': 'Push off the ground into the air',
    'KEEP': 'To hold onto something',
    'KIND': 'Nice and caring',
    'KING': 'A male ruler in a kingdom',
    'KNEE': 'The joint in the middle of your leg',
    'LADY': 'An adult woman',
    'LAMP': 'A light you can turn on',
    'LAND': 'Ground that is not water',
    'LAST': 'Coming after all the others',
    'LATE': 'After the expected time',
    'LEAF': 'A flat green part of a plant or tree',
    'LEFT': 'The opposite direction from right',
    'LIFE': 'The time when a living thing is alive',
    'LINE': 'A long narrow mark',
    'LIPS': 'The soft edges around your mouth',
    'LIVE': 'To be alive or make your home somewhere',
    'LONG': 'Not short',
    'LOOK': 'Use your eyes to see',
    'LOVE': 'A strong feeling of caring',
    'MAIN': 'The most important one',
    'MAKE': 'To create or build something',
    'MANY': 'A large number of things',
    'MEET': 'To come together with someone',
    'MILK': 'A white drink that comes from cows and other animals',
    'MIND': 'The part of you that thinks',
    'MISS': 'To not hit, catch, or find something',
    'MORE': 'A bigger amount',
    'MOVE': 'To change place or position',
    'NAME': 'The word people call you',
    'NEAR': 'Close by',
    'NECK': 'The body part between your head and shoulders',
    'NEED': 'Something you must have or do',
    'NEST': 'A home built by a bird',
    'NEWS': 'Information about things that happened',
    'NEXT': 'Coming right after this one',
    'NOSE': 'The part of your face used for smelling',
    'NOTE': 'A short written message',
    'OPEN': 'Not closed',
    'OVER': 'Above something',
    'PARK': 'A place outdoors for playing or relaxing',
    'PART': 'One piece of a whole thing',
    'PATH': 'A small way or trail to walk on',
    'PEAR': 'A sweet fruit with a narrow top',
    'PINK': 'A light red color',
    'PLAN': 'An idea for what you will do',
    'PLAY': 'To have fun with a game or toy',
    'POOR': 'Having very little money',
    'POST': 'A tall upright pole',
    'READ': 'To understand words on a page',
    'REST': 'To stop and relax for a while',
    'RING': 'A small circle worn on a finger',
    'ROAD': 'A way that cars travel on',
    'ROCK': 'A hard piece of stone',
    'ROOM': 'A space inside a building',
    'ROSE': 'A flower that often has thorns',
    'RULE': 'Something that tells what is allowed',
    'SEAT': 'A place to sit',
    'SEND': 'To make something go to another person or place',
    'SHOW': 'To let someone see something',
    'SIDE': 'One edge or part of something',
    'SIGN': 'A notice that gives information',
    'SIZE': 'How big or small something is',
    'SKIN': 'The outside covering of your body',
    'SNOW': 'Soft white flakes that fall in cold weather',
    'SOCK': 'Clothing worn on your foot inside a shoe',
    'SOFA': 'A soft seat for more than one person',
    'SOFT': 'Easy to press and not hard',
    'SOIL': 'Dirt where plants grow',
    'SOON': 'In a short time',
    'STEP': 'One movement of your foot while walking',
    'STOP': 'To not keep going',
    'SWIM': 'Move through water using your body',
    'TAKE': 'To pick up or carry something with you',
    'TALK': 'To speak with someone',
    'TELL': 'To give someone information with words',
    'THIN': 'Not thick',
    'TIME': 'What clocks measure',
    'TONE': 'The sound or feeling of a voice',
    'TOWN': 'A place where people live, smaller than a city',
    'TRUE': 'Correct and not made up',
    'TURN': 'To change direction',
    'VIEW': 'What you can see from a place',
    'WAIT': 'To stay until something happens',
    'WALL': 'A side of a room or building',
    'WANT': 'To wish to have or do something',
    'WEAK': 'Not very strong',
    'WEEK': 'Seven days',
    'WELL': 'In a good or healthy way',
    'WEST': 'The direction where the sun sets',
    'WIDE': 'Having lots of space from side to side',
    'WIND': 'Moving air you can feel',
    'WING': 'A body part that helps a bird fly',
    'WISH': 'To hope for something you want',
    'WOOD': 'The hard material inside a tree',
    'WORD': 'A group of letters with meaning',
    'WORK': 'A job or task you do',
    'WORM': 'A small long animal with no legs',
    'YEAR': 'Twelve months',
    'ISSUE': 'A topic or problem people are talking about',
    'JOINT': 'A place where two bones meet',
    'KITTY': 'A young cat',
    'KNOWN': 'Something people already know about',
    'LABOR': 'Hard work or a group of workers',
    'LARGE': 'Big in size',
    'LATER': 'At a time after now',
    'LEAST': 'The smallest amount',
    'LEAVE': 'To go away from a place',
    'LIGHT': 'What helps you see in the dark',
    'LOCAL': 'From or near the place where you live',
    'LODGE': 'A small place to stay, often in the woods',
    'LOOSE': 'Not tight or firmly attached',
    'LOWER': 'To move something down',
    'LYING': 'Resting flat or not telling the truth',
    'LYMPH': 'A clear fluid that moves through the body',
    'MAJOR': 'Very important or large',
    'MAMMA': 'Another word for mother',
    'MARRY': 'To become someone’s husband or wife',
    'MEANS': 'A way to do something',
    'MEANT': 'Intended to say or do',
    'MIGHT': 'A word meaning maybe, or great strength',
    'MILES': 'Units used to measure long distances',
    'MONEY': 'Coins and bills used to buy things',
    'MOUTH': 'The part of your face used to eat and talk',
    'MUSIC': 'Sounds arranged into songs or tunes',
    'NERVE': 'A body part that carries messages to and from the brain',
    'NEVER': 'Not at any time',
    'NORTH': 'The direction opposite south',
    'OCCUR': 'To happen',
    'OFTEN': 'Many times',
    'ORDER': 'A request for something or a neat arrangement',
    'OTHER': 'A different one',
    'OUGHT': 'A word meaning should',
    'PAPER': 'A thin material used for writing or drawing',
    'PARTY': 'A gathering where people celebrate',
    'PEACE': 'A calm time without fighting',
    'PEACH': 'A soft, sweet fruit with fuzzy skin',
    'PLACE': 'A spot or location',
    'PLAIN': 'Simple, or a wide flat area of land',
    'POINT': 'A sharp tip or a main idea',
    'PORCH': 'A covered area by the entrance of a house',
    'POWER': 'The ability or energy to make something happen',
    'PRESS': 'To push down on something',
    'PROVE': 'To show that something is true',
    'QUEEN': 'A female ruler in a royal family',
    'QUICK': 'Fast',
    'QUIET': 'Making very little sound',
    'QUITE': 'Very or completely',
    'RANKS': 'Rows or levels in an organization',
    'RAPID': 'Very fast',
    'REACH': 'To stretch out and get to something',
    'READY': 'Prepared to begin',
    'REPLY': 'An answer to what someone said or wrote',
    'RIGHT': 'Correct, or the direction opposite left',
    'RIVER': 'A large stream of flowing water',
    'ROUND': 'Shaped like a circle or ball',
    'ROYAL': 'Connected with a king or queen',
    'SENSE': 'One way your body notices the world, like sight or smell',
    'SEVEN': 'The number after six',
    'SHAFT': 'A long narrow rod or passage',
    'SHALL': 'A word used to talk about what will happen',
    'SHARP': 'Having a pointed edge that can cut',
    'SHIRT': 'Clothing worn on the upper body',
    'SHOCK': 'A sudden surprise or jolt',
    'SHORT': 'Not long or tall',
    'SHOWN': 'Made visible or displayed',
    'SIGHT': 'Something you can see, or the ability to see',
    'SINCE': 'From a past time until now',
    'SKULL': 'The bones that protect your brain',
    'SLAVE': 'A person forced to work without freedom',
    'SLEEP': 'Rest your body and mind at night',
    'SMALL': 'Little in size',
    'SMOKE': 'The gray cloud that rises from a fire',
    'SNAKE': 'A long reptile with no legs',
    'SORRY': 'A word you say when you regret something',
    'SOUND': 'Something you can hear',
    'SOUTH': 'The direction opposite north',
    'SPEAK': 'To say words out loud',
    'SPENT': 'Used up or paid out',
    'SPITE': 'A wish to annoy or hurt someone',
    'SPOKE': 'Talked, or one of the rods in a wheel',
    'SPOON': 'A utensil with a small bowl on the end',
    'STAFF': 'A group of workers, or a long stick',
    'STAGE': 'A raised area where performers appear',
    'STAND': 'To be upright on your feet',
    'STATE': 'A part of a country, or a condition something is in',
    'STILL': 'Not moving',
    'STONE': 'A hard piece of rock',
    'STOOD': 'Was upright on your feet',
    'STORM': 'Bad weather with wind, rain, snow, or thunder',
    'STORY': 'A tale about people or events',
    'STUDY': 'To learn about something carefully',
    'SUITE': 'A set of connected rooms',
    'TABLE': 'Furniture with a flat top and legs',
    'TAKEN': 'Picked up, carried, or chosen',
    'TEARS': 'Drops that come from your eyes when you cry',
    'TEETH': 'Hard white parts in your mouth used for biting',
    'THANK': 'To tell someone you are grateful',
    'THEIR': 'Belonging to them',
    'THERE': 'In or at that place',
    'THESE': 'More than one thing nearby',
    'THICK': 'Having a lot of width from one side to the other',
    'THING': 'An object, idea, or item',
    'THINK': 'To use your mind to consider something',
    'THIRD': 'The one after second',
    'THOSE': 'More than one thing farther away',
    'THREE': 'The number after two',
    'THREW': 'Sent something through the air with your hand',
    'TIGER': 'A large striped wild cat',
    'TOAST': 'Bread browned by heat',
    'TODAY': 'This day',
    'TOUCH': 'To put your hand or finger on something',
    'TRADE': 'To exchange one thing for another',
    'TRIED': 'Made an attempt',
    'TRUNK': 'The main stem of a tree or a large storage box',
    'TRUTH': 'Something that is true',
    'TWICE': 'Two times',
    'ULCER': 'A sore that forms on skin or inside the body',
    'UNCLE': 'The brother of a parent, or an aunt’s husband',
    'UNDER': 'Below something',
    'UNION': 'A joining together of people or things',
    'UNTIL': 'Up to a certain time',
    'UPPER': 'Higher than another part',
    'USUAL': 'What normally happens',
    'VALUE': 'How useful, important, or costly something is',
    'VISIT': 'To go see a person or place for a while',
    'VOICE': 'The sound a person makes when speaking',
    'WATER': 'The clear liquid we drink',
    'WHERE': 'A question word asking about a place',
    'WHICH': 'A question word asking you to choose',
    'WHILE': 'A period of time',
    'WHITE': 'The color of fresh snow',
    'WHOLE': 'All of something, with no part missing',
    'WHOSE': 'A question word asking who owns something',
    'WOMAN': 'An adult female person',
    'WOMEN': 'More than one adult female person',
    'WORLD': 'Earth and all the people and places on it',
    'WOULD': 'A word used to talk about a possible action',
    'WOUND': 'An injury such as a cut',
    'WRITE': 'To make words with letters',
    'WRONG': 'Not correct',
    'WROTE': 'Made words on paper or a screen in the past',
    'YOUNG': 'Not old',
    'ZEBRA': 'An animal with black-and-white stripes',
    'ACROSS': 'From one side to the other',
    'ACTION': 'Something that is done',
    'ACTIVE': 'Moving or doing things often',
    'AFFAIR': 'An event, matter, or situation',
    'AFRAID': 'Feeling scared',
    'AGREED': 'Had the same opinion',
    'ALMOST': 'Very close, but not completely',
    'ALWAYS': 'Every time',
    'AMOUNT': 'How much of something there is',
    'ANSWER': 'What you say or write in response to a question',
    'ANYONE': 'Any person at all',
    'APPEAR': 'To come into view',
    'AROUND': 'On every side or nearby',
    'ARTERY': 'A blood vessel that carries blood away from the heart',
    'ASLEEP': 'Sleeping',
    'ASSUME': 'To suppose something is true without knowing for sure',
    'ATTACK': 'To try to hurt or defeat',
    'BASKET': 'A container often woven from strips of material',
    'BATTLE': 'A fight between groups',
    'BEAUTY': 'The quality of being lovely to see or experience',
    'BECAME': 'Changed into something',
    'BECOME': 'To change into something',
    'BEFORE': 'Earlier than something else',
    'BEHIND': 'At the back of something',
    'BESIDE': 'Next to',
    'BETTER': 'More good than before',
    'BEYOND': 'Farther than or past something',
    'BRIDGE': 'A structure that lets you cross over water or a road',
    'BRIGHT': 'Giving lots of light or vivid in color',
    'BROKEN': 'Damaged and not working properly',
    'BUTTON': 'A small fastener on clothing or a control you press',
    'CANDLE': 'Wax with a wick that gives light when lit',
    'CANNON': 'A large old-fashioned weapon that fires heavy balls',
    'CANNOT': 'Another way to say can not',
    'CAUGHT': 'Grabbed, trapped, or found',
    'CAVITY': 'A hole, especially one in a tooth',
    'CENTER': 'The middle part',
    'CHANCE': 'A possibility that something might happen',
    'CHANGE': 'To make or become different',
    'CHARGE': 'To ask a price, fill with energy, or rush forward',
    'CHOSEN': 'Picked from a group',
    'CHURCH': 'A building where many Christians worship',
    'CIRCLE': 'A round shape with no corners',
    'COLOUR': 'The British spelling of color',
    'COMING': 'Moving toward this place',
    'COMMON': 'Seen or found often',
    'CORNER': 'The place where two edges meet',
    'COTTON': 'A soft plant fiber used to make cloth',
    'COURSE': 'A path, direction, or class you take',
    'DANGER': 'Something that could cause harm',
    'DEEPLY': 'Far down or with strong feeling',
    'DEGREE': 'A unit for measuring temperature or angles',
    'DEMAND': 'To ask for something strongly',
    'DESIRE': 'A strong wish for something',
    'DINNER': 'The main meal often eaten in the evening',
    'DIRECT': 'Straight, or to guide someone',
    'DOCTOR': 'A person trained to care for sick or injured people',
    'DURING': 'While something is happening',
    'EASILY': 'Without much trouble',
    'EFFECT': 'A result caused by something',
    'EFFORT': 'The work you put into doing something',
    'EITHER': 'One or the other of two choices',
    'EMPIRE': 'A group of lands ruled by one leader or government',
    'ENOUGH': 'As much as is needed',
    'ESCAPE': 'To get away from a place or danger',
    'ESTATE': 'A large property or everything a person owns',
    'EXCEPT': 'Leaving out one thing',
    'EXTENT': 'How far something reaches',
    'FALLEN': 'Dropped down to the ground',
    'FAMILY': 'A group of related people',
    'FATHER': 'A male parent',
    'FELLOW': 'A person or companion',
    'FIGURE': 'A shape, number, or person',
    'FINGER': 'One of the five parts at the end of your hand',
    'FIRING': 'Shooting, heating, or removing someone from a job',
    'FIRMLY': 'In a strong or steady way',
    'FOLLOW': 'To go after someone or something',
    'FORGET': 'To fail to remember',
    'FORMER': 'From an earlier time',
    'FOURTH': 'The one after third',
    'FRIEND': 'A person you like and trust',
    'FUTURE': 'The time that has not happened yet',
    'GENIUS': 'A person with extremely great ability or ideas',
    'GIVING': 'Handing something to someone',
    'GLANCE': 'A quick look',
    'GLANDS': 'Body parts that make and release substances',
    'GROUND': 'The surface of the earth beneath your feet',
    'GROWTH': 'The process of getting bigger',
    'GUARDS': 'People who protect a place or person',
    'GUESTS': 'People invited to visit or attend',
    'GUITAR': 'A musical instrument with strings',
    'HAPPEN': 'To take place',
    'HARDLY': 'Almost not at all',
    'HAVING': 'Owning, holding, or experiencing something',
    'HEALTH': 'How well your body and mind are doing',
    'HEAVEN': 'A place of perfect happiness in many religions',
    'HIGHER': 'Farther up',
    'INDEED': 'A word used to strongly confirm something',
    'INJURY': 'Damage or harm to the body',
    'ISLAND': 'Land completely surrounded by water',
    'ITSELF': 'That exact thing, not another one',
    'KINDLY': 'In a friendly and caring way',
    'LARGER': 'Bigger than something else',
    'LATTER': 'The second of two things just mentioned',
    'LESION': 'An area of damaged or unusual body tissue',
    'LETTER': 'A written character like A or B, or a message in an envelope',
    'LIABLE': 'Likely to happen or legally responsible',
    'LIKELY': 'Probably going to happen',
    'LISTEN': 'To pay attention to sound',
    'LITTLE': 'Small in size or amount',
    'LIVING': 'Being alive',
    'LONGER': 'Having more length or lasting more time',
    'MAINLY': 'Mostly',
    'MAKING': 'Creating or building something',
    'MANNER': 'A way of doing something',
    'MARROW': 'Soft tissue inside many bones',
    'MASTER': 'A person who is very skilled at something',
    'MATTER': 'A subject, or the material everything is made of',
    'MERELY': 'Only or simply',
    'METHOD': 'A way of doing something',
    'MIDDLE': 'The part halfway between two ends',
    'MINUTE': 'Sixty seconds',
    'MOMENT': 'A very short amount of time',
    'MONTHS': 'Units of the year; there are twelve in one year',
    'MOTHER': 'A female parent',
    'MOVING': 'Changing position or going somewhere',
    'MUCOUS': 'A thick slippery substance made by the body',
    'MUSCLE': 'Body tissue that helps you move',
    'MYSELF': 'The word a speaker uses to mean their own self',
    'NATION': 'A country and its people',
    'NATURE': 'Plants, animals, weather, and the outdoor world',
    'NEARER': 'Closer than before',
    'NEARLY': 'Almost',
    'NORMAL': 'Usual or expected',
    'NOTICE': 'To see or become aware of something',
    'NUMBER': 'A symbol or word used for counting',
    'OBJECT': 'A thing you can see or touch',
    'OEDEMA': 'Swelling caused by extra fluid in body tissue',
    'OFFICE': 'A place where people work at desks',
    'ORIGIN': 'The place or point where something begins',
    'PEOPLE': "More than one person",
    'PERIOD': "The dot at the end of a sentence",
    'PERSON': "One human being",
    'PLANET': "A large world that travels around a star",
    'PLEASE': "A polite word used when asking",
    'POLICE': "People whose job is to help enforce laws",
    'POLICY': "A rule or plan used by a group",
    'PRETTY': "Nice or pleasing to look at",
    'PRINCE': "The son of a king or queen",
    'PUBLIC': "Open or available to everyone",
    'RARELY': "Not very often",
    'RATHER': "More willingly, or instead",
    'REALLY': "Truly or actually",
    'REASON': "Why something happened or was done",
    'REGARD': "Respect or careful attention",
    'REGION': "A large area of land",
    'REMAIN': "To stay behind or still be there",
    'REPAIR': "To fix something that is broken",
    'REPORT': "A spoken or written account of facts",
    'RESULT': "What happens because of an action",
    'RETURN': "To come or go back",
    'RIDING': "Traveling on a bike, horse, or vehicle",
    'RISING': "Moving upward",
    'RUBLES': "Money used in Russia",
    'SAYING': "Speaking words, or a familiar phrase",
    'SECOND': "Coming after first, or a short unit of time",
    'SECRET': "Something meant to be kept private",
    'SECURE': "Safe and protected",
    'SEEING': "Using your eyes to notice something",
    'SELDOM': "Not often",
    'SENATE': "A group of lawmakers in a government",
    'SERIES': "A group of things that come one after another",
    'SEVERE': "Very serious or strong",
    'SHEATH': "A cover that holds a blade",
    'SHOULD': "A word used for what is a good idea to do",
    'SILENT': "Making no sound",
    'SILVER': "A shiny gray metal",
    'SIMPLE': "Easy to understand or not complicated",
    'SIMPLY': "In an easy or plain way",
    'SINGLE': "Only one",
    'SISTER': "A female sibling",
    'SLIGHT': "Small or not very strong",
    'SLOWLY': "At a low speed",
    'SOCCER': "A sport where players kick a ball toward a goal",
    'SOCIAL': "Having to do with people spending time together",
    'SOUGHT': "Tried to find or get",
    'SOURCE': "Where something comes from",
    'SPEECH': "Words spoken to an audience",
    'SPIRIT': "A person\u2019s mood, energy, or inner self",
    'SPOKEN': "Said out loud",
    'SPREAD': "To open, stretch, or move over a wider area",
    'SPRING': "The season after winter, or something that bounces",
    'SQUARE': "A shape with four equal sides",
    'STREAM': "A small flowing body of water",
    'STREET': "A road in a town or city",
    'STRONG': "Having lots of power or strength",
    'STRUCK': "Hit something",
    'SUDDEN': "Happening quickly and without warning",
    'SUMMER': "The warm season after spring",
    'SUPPLY': "An amount of something ready to be used",
    'SYSTEM': "A group of parts that work together",
    'TAKING': "Picking up, carrying, or receiving something",
    'TARIFF': "A tax charged on goods brought into a country",
    'TENDER': "Gentle, soft, or easy to hurt",
    'TENDON': "A strong band that connects muscle to bone",
    'THEORY': "An idea meant to explain how something works",
    'THIRTY': "The number after twenty-nine",
    'THOUGH': "Even if, or despite that",
    'THROWN': "Sent through the air by hand",
    'TISSUE': "A group of similar cells in a body",
    'TOWARD': "In the direction of",
    'TREATY': "A formal agreement between countries",
    'TROOPS': "Groups of soldiers",
    'TRYING': "Making an effort to do something",
    'TUMOUR': "An unusual lump or growth in the body",
    'TWENTY': "Two groups of ten",
    'UNABLE': "Not able to do something",
    'UNLESS': "Except if something happens",
    'USEFUL': "Helpful for doing something",
    'VALLEY': "Low land between hills or mountains",
    'VESSEL': "A container, boat, or tube that carries fluid",
    'WEALTH': "A large amount of money or valuable things",
    'WEIGHT': "How heavy something is",
    'WINDOW': "An opening with glass that lets in light",
    'WITHIN': "Inside or not farther than",
    'YELLOW': "The color of a lemon or the sun in many drawings",
    'ABSENCE': "When someone or something is not there",
    'ACCOUNT': "A record of money, or a profile you use to sign in",
    'ADDRESS': "Where a home or building is located",
    'ADVANCE': "To move forward",
    'AGAINST': "Touching, opposing, or on the other side from",
    'AIRSHIP': "A large aircraft held up by a gas-filled body",
    'ALREADY': "Before now or sooner than expected",
    'ANGRILY': "In a mad or upset way",
    'ANOTHER': "One more or a different one",
    'ARRIVAL': "The act of reaching a place",
    'ATTEMPT': "A try at doing something",
    'BATTERY': "Something that stores energy for a device",
    'BECAUSE': "A word that gives a reason",
    'BELIEVE': "To think something is true",
    'BENEATH': "Under something",
    'BETWEEN': "In the space separating two things",
    'BLANKET': "A warm covering used on a bed",
    'BROTHER': "A male sibling",
    'BROUGHT': "Carried or took something to a place",
    'BURNING': "On fire or feeling very hot",
    'CAPITAL': "A main city, a big letter, or money used to start something",
    'CAPTAIN': "The person in charge of a team, ship, or group",
    'CAVALRY': "Soldiers who traditionally fought on horseback",
    'CENTRAL': "In or near the middle",
    'CENTURY': "A period of one hundred years",
    'CERTAIN': "Sure or known to be true",
    'CHAPTER': "One main section of a book",
    'CHIEFLY': "Mostly or mainly",
    'CHRONIC': "Lasting a long time or happening often",
    'CLEARLY': "In a way that is easy to see or understand",
    'CLOSELY': "With careful attention or from a short distance",
    'COLONEL': "A military officer rank",
    'COMMAND': "An order, or control over something",
    'COMPANY': "A business or a group of people together",
    'CONTACT': "Communication or connection with someone",
    'CONTROL': "The power to direct or manage something",
    'COUNCIL': "A group of people chosen to make decisions",
    'COUNTRY': "A nation with its own government",
    'CUPCAKE': "A small cake baked for one person",
    'CURRENT': "Happening now, or a flow of water or electricity",
    'DEFENSE': "Protection from attack or harm",
    'DESPITE': "Even though something is true",
    'DETAILS': "Small facts or pieces of information",
    'DIFFUSE': "To spread out over a wide area",
    'DISEASE': "An illness that affects the body",
    'EMPEROR': "A ruler of an empire",
    'ENGLISH': "The language used in places such as the United States and Britain",
    'EQUALLY': "In the same amount or degree",
    'EVENING': "The part of the day after afternoon",
    'EVIDENT': "Easy to see or understand",
    'EXAMPLE': "Something that shows what a kind or idea is like",
    'EXPLAIN': "To make something easier to understand",
    'EXPRESS': "To show a thought or feeling, or move quickly",
    'EXTREME': "Very great or far from the usual",
    'FARMERS': "People who grow crops or raise animals",
    'FARTHER': "At a greater distance",
    'FEDERAL': "Relating to a country\u2019s national government",
    'FEELING': "An emotion or a sense in the body",
    'FIBROUS': "Made of or containing threadlike fibers",
    'FINALLY': "At last or at the end",
    'FIREFLY': "A small insect that can glow",
    'FOREIGN': "From another country",
    'FORWARD': "Toward the front or ahead",
    'FREEDOM': "The ability to act or choose without unfair limits",
    'FURTHER': "More distant or additional",
    'GENERAL': "Common or broad, or a high-ranking military officer",
    'GETTING': "Receiving, becoming, or going to obtain something",
    'GREATER': "Larger or more important",
    'GROWING': "Getting bigger, older, or more numerous",
    'HEALING': "Getting better after being hurt or sick",
    'HEARING': "The sense used to notice sounds",
    'HERSELF': "A word a girl or woman uses when the action points back to her",
    'HIGHEST': "At the greatest height or level",
    'HIMSELF': "A word a boy or man uses when the action points back to him",
    'HISTORY': "The study or story of what happened in the past",
    'HOLDING': "Keeping something in your hand or possession",
    'HOWEVER': "But, or in whatever way",
    'HUNDRED': "Ten groups of ten",
    'HUSBAND': "A married man",
    'IMAGINE': "To make a picture or idea in your mind",
    'IMMENSE': "Extremely large",
    'INSTANT': "A very short moment",
    'INSTEAD': "In place of something else",
    'JOURNEY': "A trip from one place to another",
    'JUSTICE': "Fair treatment under rules or laws",
    'KNOWING': "Having information or understanding",
    'LEADERS': "People who guide a group",
    'LEADING': "Being in front or guiding others",
    'LEAVING': "Going away from a place",
    'LIBERTY': "Freedom to act or choose",
    'LOOKING': "Using your eyes to see something",
    'MAJESTY': "Great royal dignity or a title for a king or queen",
    'MARSHAL': "An officer or official who organizes or commands",
    'MEANING': "What a word, sign, or idea stands for",
    'MEASURE': "To find the size, amount, or length of something",
    'MEETING': "A time when people come together to talk or work",
    'MEMBERS': "People who belong to a group",
    'MILLION': "One thousand thousands",
    'MONSTER': "A scary make-believe creature",
    'MORNING': "The early part of the day before noon",
    'NATURAL': "Found in nature or not made artificially",
    'NEITHER': "Not one and not the other",
    'NOTHING': "Not anything at all",
    'OBVIOUS': "Easy to notice or understand",
    'OFFICER': "A person with an official job in police, military, or an organization",
    'OPENING': "A hole, beginning, or available position",
    'OPINION': "What someone thinks or believes",
    'OUTSIDE': "Not inside",
    'PAINFUL': "Causing hurt or discomfort",
    'PANCAKE': "A flat round breakfast food cooked in a pan",
    'PASSAGE': "A section of writing or a way through",
    'PASSING': "Moving by or successfully completing something",
    'PATIENT': "A person receiving medical care, or able to wait calmly",
    'PEASANT': "A poor farm worker in historical societies",
    'PENGUIN': "A black-and-white bird that swims but cannot fly",
    'PERHAPS': "Maybe; possibly",
    'POPULAR': "Liked or enjoyed by many people",
    'PORTION': "A part or share of something",
    'PRESENT': "Here now, or a gift you give someone",
    'PREVENT': "To stop something from happening",
    'PRIMARY': "First or most important",
    'PRIVATE': "Not open or shared with everyone",
    'PROBLEM': "Something difficult that needs an answer",
    'PROCESS': "A series of steps used to do something",
    'PRODUCE': "To make or create something",
    'PROJECT': "A planned piece of work or activity",
    'PROMISE': "A serious agreement to do something",
    'PURPOSE': "The reason something exists or is done",
    'PUTTING': "Placing something somewhere",
    'QUICKLY': "At a fast speed",
    'QUIETLY': "With very little noise",
    'RAILWAY': "A track and system used by trains",
    'RAISING': "Lifting or moving something higher",
    'RAPIDLY': "Very quickly",
    'READILY': "Easily or willingly",
    'READING': "Looking at written words and understanding them",
    'RECEIVE': "To get something that is sent or given",
    'REGULAR': "Usual, normal, or happening on a pattern",
    'REMOVAL': "The act of taking something away",
    'RESPECT': "Care and admiration shown toward someone or something",
    'RETREAT': "To move back or away",
    'RUNNING': "Moving quickly on foot",
    'RUPTURE': "A break or tear in something",
    'SECTION': "One part of a larger whole",
    'SERIOUS': "Important and not silly or playful",
    'SERVICE': "Work done to help someone",
    'SEVERAL': "More than two but not a very large number",
    'SHOWING': "Letting someone see something",
    'SILENCE': "A time or place with no sound",
    'SIMILAR': "Almost the same, but not exactly",
    'SITTING': "Resting with your body supported on a seat",
    'SLAVERY': "A system in which people are forced to work without freedom",
    'SMILING': "Making a happy expression with your mouth",
    'SOCIETY': "A large group of people living together in a community",
    'SOLDIER': "A person who serves in an army",
    'SOMEONE': "An unknown or unnamed person",
    'SPECIAL': "Different in a good or important way",
    'STRANGE': "Unusual or unfamiliar",
    'SUBJECT': "A topic being discussed or studied",
    'SUCCESS': "Doing or achieving what you hoped to do",
    'SUPPORT': "To help hold up, encourage, or assist",
    'SUPREME': "Highest or greatest in rank or power",
    'SURFACE': "The outside or top layer of something",
    'TALKING': "Speaking with someone",
    'TEACHER': "A person who helps others learn",
    'TELLING': "Speaking or giving information",
    'THOUGHT': "An idea in your mind",
    'THROUGH': "Going in one side and out the other",
    'TRACTOR': "A powerful farm vehicle used to pull equipment",
    'TURNING': "Changing direction or rotating",
    'UNICORN': "A make-believe horse with one horn",
    'UNIFORM': "Matching clothing worn by members of a group",
    'UNKNOWN': "Not known or not identified",
    'USUALLY': "Most of the time",
    'VARIETY': "A mix of different kinds of things",
    'VARIOUS': "Several different kinds",
    'VICTORY': "Winning a game, contest, or battle",
    'VILLAGE': "A small community, usually smaller than a town",
    'VISITOR': "A person who comes to see a place or person",
    'WAITING': "Staying until something happens",
    'WALKING': "Moving on foot at a normal pace",
    'WEARING': "Having clothing or another item on your body",
    'WESTERN': "Located in or related to the west",
    'WHETHER': "A word used when talking about two possibilities",
    'WISHING': "Hoping for something you want",
    'WITHOUT': "Not having or using something",
    'WRITING': "Making words with letters on paper or a screen",
    'WRITTEN': "Put into words on paper or a screen",
    'ACTIVITY': "Something you do for work, fun, or practice",
    'ADDITION': "Putting something extra in, or adding numbers",
    'ADJACENT': "Right next to something",
    'ADJUTANT': "An officer who helps a more senior military officer",
    'ALTHOUGH': "Even though; despite the fact that",
    'AMERICAN': "A person or thing from the United States",
    'ANYTHING': "Any object, event, or idea at all",
    'ARTICLES': "Written pieces in a newspaper, magazine, or website",
    'ATTITUDE': "The way you think or feel about something",
    'BACTERIA': "Tiny living things, some helpful and some harmful",
    'BECOMING': "Starting to be something different",
    'BLEEDING': "Losing blood from the body",
    'BRANCHES': "Parts of a tree that grow out from the trunk",
    'BUSINESS': "Work involving making, buying, or selling things or services",
    'CAMPAIGN': "An organized effort to achieve a goal",
    'CARRIAGE': "A wheeled vehicle, often pulled by horses",
    'CARRYING': "Holding something while moving it",
    'CELLULAR': "Made of or related to tiny living cells",
    'CHARMING': "Pleasant, friendly, or delightful",
    'CHILDREN': "More than one child",
    'CITIZENS': "People who legally belong to a country",
    'CLINICAL': "Related to medical care or examining patients",
    'COLONIAL': "Related to a colony or colonies",
    'COLONIES': "Places controlled or settled by people from another country",
    'COMMERCE': "The buying and selling of goods",
    'COMPLETE': "Finished, with nothing missing",
    'CONFLICT': "A serious disagreement or fight",
    'CONGRESS': "A group of elected lawmakers in the United States",
    'CONSIDER': "To think carefully about something",
    'CONSISTS': "Is made up of certain parts",
    'CONSTANT': "Staying the same or happening all the time",
    'CONTRARY': "Opposite or very different",
    'COUNTESS': "A woman with a noble title",
    'DARKNESS': "The absence of light",
    'DAUGHTER': "A female child in a family",
    'DEFINITE': "Certain and clear",
    'DIRECTLY': "In a straight way, or without delay",
    'DISTANCE': "The space between two places or things",
    'DIVISION': "The act of splitting into parts, or a math operation",
    'DOCTRINE': "A set of beliefs or teachings",
    'DOMESTIC': "Related to home or to one country",
    'DREADFUL': "Very bad or unpleasant",
    'DRESSING': "Putting on clothes, or a sauce used on food",
    'ECONOMIC': "Related to money, jobs, trade, and resources",
    'ELECTION': "A vote used to choose a leader or representative",
    'ELEMENTS': "Basic parts that make up something",
    'ENORMOUS': "Extremely large",
    'ENTERING': "Going into a place",
    'ENTIRELY': "Completely; in every way",
    'EVERYONE': "Every person in a group",
    'EVIDENCE': "Facts or signs that help show what is true",
    'EXTERNAL': "On or coming from the outside",
    'FAMILIAR': "Known because you have seen or experienced it before",
    'FEATURES': "Important or noticeable parts of something",
    'FIGHTING': "Taking part in a fight or struggle",
    'FOREHEAD': "The part of your face above your eyebrows",
    'FORMERLY': "In the past; before now",
    'FRACTURE': "A crack or break, especially in a bone",
    'FRONTIER': "The edge of settled land or a boundary region",
    'GLANCING': "Looking quickly for a short moment",
    'GOVERNOR': "The elected leader of a state",
    'GREATEST': "Best, largest, or most important",
    'HANDSOME': "Good-looking, often used to describe a man or boy",
    'INCREASE': "To become or make something larger or greater",
    'INDUSTRY': "Businesses that make the same kind of product or service",
    'INFANTRY': "Soldiers who fight mainly on foot",
    'INNOCENT': "Not guilty of doing something wrong",
    'INTEREST': "Curiosity or attention toward something",
    'INTERNAL': "On or happening inside",
    'LAUGHING': "Making sounds because something is funny or joyful",
    'LAUGHTER': "The sound people make when they laugh",
    'MAJORITY': "More than half of a group",
    'MARRIAGE': "A legal or personal partnership between spouses",
    'MATERIAL': "What something is made from",
    'MEMBRANE': "A thin layer that covers or separates something",
    'MILITARY': "The armed forces of a country",
    'MINISTER': "A government official or a religious leader",
    'MOREOVER': "Also; in addition to what was just said",
    'MOVEMENT': "The act of changing position or place",
    'MULTIPLE': "More than one; many of the same kind",
    'MUSCULAR': "Related to muscles, or having strong muscles",
    'NATIONAL': "Related to an entire country",
    'NONSENSE': "Words or ideas that do not make sense",
    'NORTHERN': "Located in or related to the north",
    'OFFICIAL': "Approved by an authority, or a person with a public duty",
    'OPPOSITE': "Completely different or across from something",
    'ORDINARY': "Normal and not unusual",
    'ORIGINAL': "The first one, not a copy",
    'PECULIAR': "Strange or unusual",
    'PERSONAL': "Belonging or relating to one particular person",
    'PLEASANT': "Nice, enjoyable, or friendly",
    'PLEASURE': "A feeling of happiness or enjoyment",
    'POINTING': "Showing a direction with a finger or object",
    'POLITICS': "Activities and ideas about how governments are run",
    'POSITION': "A place, location, or way something is arranged",
    'POSSIBLE': "Able to happen or be done",
    'POWERFUL': "Having a lot of strength or influence",
    'PRACTICE': "Repeated work that helps you improve a skill",
    'PRESENCE': "The fact that someone or something is there",
    'PRESSING': "Pushing firmly against something",
    'PRESSURE': "Force pushing on something, or a feeling of urgency",
    'PREVIOUS': "Coming before the current one",
    'PRINCESS': "A female member of a royal family",
    'PROBABLY': "Very likely, though not completely certain",
    'PROGRESS': "Movement toward a goal or improvement",
    'PROPERTY': "Something that belongs to a person or group",
    'QUARTERS': "Four equal parts, or places where people live or stay",
    'QUESTION': "Something asked because you want an answer",
    'REACTION': "What happens in response to something",
    'REGIMENT': "A large organized group of soldiers",
    'RELATION': "A connection between people or things",
    'REMEMBER': "To bring something back into your mind",
    'SCARCELY': "Hardly; almost not at all",
    'SEPARATE': "To divide or keep things apart",
    'SERVANTS': "People employed to do household or personal work",
    'SHOULDER': "The body part connecting your arm to your upper body",
    'SHOUTING': "Speaking very loudly",
    'SILENTLY': "Without making noise",
    'SLIGHTLY': "A little bit",
    'SMOLENSK': "A city in western Russia",
    'SOLUTION': "An answer to a problem",
    'SOUTHERN': "Located in or related to the south",
    'SPEAKING': "Using your voice to say words",
    'SPLENDID': "Excellent or very impressive",
    'SQUADRON': "An organized group of military aircraft, ships, or soldiers",
    'STANDING': "Being upright on your feet",
    'STRAIGHT': "Not bent or curved",
    'STRENGTH': "The ability to be strong or powerful",
    'STRUGGLE': "A difficult effort or fight",
    'SUDDENLY': "Quickly and unexpectedly",
    'SUFFRAGE': "The right to vote in political elections",
    'SURGICAL': "Related to an operation performed by a doctor",
    'SURPRISE': "Something unexpected, or the feeling it causes",
    'SWELLING': "A body part becoming larger, often from injury",
    'SYMPTOMS': "Signs that may show someone is sick or injured",
    'SYPHILIS': "A bacterial infection that can make a person ill",
    'TENDENCY': "A usual way of behaving or a direction things often go",
    'TERRIBLE': "Very bad, unpleasant, or frightening",
    'THINKING': "Using your mind to consider ideas",
    'THOUSAND': "The number 1,000",
    'TOGETHER': "With each other or in the same place",
    'TOMORROW': "The day after today",
    'WHATEVER': "Anything or everything that fits the situation",
    'YOURSELF': "The person you are, used when talking about you",
  };

  if (!window.ANSWER_WORDS || typeof window.ANSWER_WORDS !== 'object') {
    window.SNOWMAN_WORDS = [];
    window.SNOWMAN_WORD_SOURCE_ERROR = true;
    return;
  }

  const words = [];
  for (let length = 4; length <= 8; length++) {
    const shared = Array.isArray(window.ANSWER_WORDS[String(length)])
      ? window.ANSWER_WORDS[String(length)]
      : (Array.isArray(window.ANSWER_WORDS[length]) ? window.ANSWER_WORDS[length] : []);
    for (const rawWord of shared) {
      const word = String(rawWord).trim().toUpperCase();
      if (!/^[A-Z]+$/.test(word) || word.length !== length) continue;
      words.push({
        word,
        clue: clueOverrides[word] || 'No clue for this word yet — try a letter!'
      });
    }
  }

  window.SNOWMAN_WORDS = words;
  window.SNOWMAN_WORD_SOURCE = 'Learn to Readle reviewed answer bank';
})();
