// Snowman v1.6: Learn to Readle's reviewed answers.js is the single source of secret words.
// This file stores only Snowman-specific clue overrides and adapts the shared word bank.
(() => {
  'use strict';

  const clueOverrides = {
    'ALSO': 'Another way to say too',
    'AMID': 'In the middle of',
    'BEEN': 'A form of the word be',
    'BERG': 'A large piece of floating ice',
    'CAME': 'Moved toward this place',
    'CASE': 'A container or a situation',
    'COME': 'Move toward this place',
    'DEAR': 'Loved or special to you',
    'DIED': 'Stopped being alive',
    'DOES': 'A form of the word do',
    'DONE': 'Finished',
    'DREW': 'Made a picture with a pencil',
    'DUTY': 'A job you are responsible for',
    'ELSE': 'Another choice or something different',
    'EVEN': 'Flat, equal, or divisible by two',
    'EVER': 'At any time',
    'FACT': 'Something that is true',
    'FATE': 'What is supposed to happen',
    'FEAR': 'The feeling of being scared',
    'FEEL': 'To notice with touch or emotion',
    'FELL': 'Dropped down',
    'FELT': 'Noticed by touch or emotion',
    'FIRM': 'Strong and not soft',
    'FORM': 'A shape or a paper to fill out',
    'FROM': 'Starting at a place or person',
    'FULL': 'Holding as much as possible',
    'GAVE': 'Handed something to someone',
    'GONE': 'No longer here',
    'GREW': 'Got bigger or older',
    'HAVE': 'To own or hold something',
    'HELD': 'Kept in your hand',
    'HERE': 'In this place',
    'HOLD': 'Keep something in your hand',
    'INTO': 'Moving to the inside of',
    'JUST': 'Fair, exact, or only a moment ago',
    'KEPT': 'Held onto or saved',
    'KNEW': 'Already understood something',
    'KNOW': 'To understand or be aware of',
    'LAID': 'Put something down',
    'LEAD': 'To guide the way',
    'LESS': 'A smaller amount',
    'LIKE': 'To enjoy something or be similar',
    'LIMB': 'An arm, leg, or large tree branch',
    'LORD': 'A title for an important ruler',
    'LOSS': 'When something is no longer yours',
    'LOST': 'Unable to find the way or something missing',
    'MADE': 'Created or built',
    'MAID': 'A person who helps clean a home',
    'MASS': 'A large amount or how much matter something has',
    'MEAN': 'To intend or to stand for something',
    'MOST': 'The greatest amount',
    'MUCH': 'A large amount',
    'MUST': 'Something you have to do',
    'NONE': 'Not even one',
    'ONCE': 'One time',
    'ONLY': 'No others besides this one',
    'PAID': 'Gave money for something',
    'PAIN': 'A hurt feeling in your body',
    'PALE': 'Light in color',
    'PASS': 'Go by or hand something along',
    'PAST': 'A time that already happened',
    'RAYS': 'Lines of light from the sun',
    'REAL': 'Actually true or existing',
    'RICH': 'Having lots of money or a strong flavor',
    'RISE': 'Move upward',
    'RODE': 'Traveled on a bike, horse, or vehicle',
    'SAID': 'Spoke some words',
    'SAKE': 'For the purpose or benefit of something',
    'SAME': 'Not different',
    'SAVE': 'Keep safe or keep for later',
    'SCAR': 'A mark left after a cut heals',
    'SEEM': 'To appear to be',
    'SEEN': 'Already looked at',
    'SELF': 'Your own person',
    'SENT': 'Made something go to another place',
    'SHOT': 'A quick try, a photograph, or something fired',
    'SOME': 'A certain amount but not all',
    'SORT': 'A kind or type',
    'SOUL': 'The inner spirit of a person',
    'SUCH': 'Of that kind',
    'SURE': 'Certain or confident',
    'TERM': 'A word, a period of time, or a school session',
    'THAN': 'Used when comparing two things',
    'THAT': 'Points to a certain thing',
    'THEM': 'A word for those people or things',
    'THEN': 'At that time or next',
    'THEY': 'A word for a group of people or things',
    'THIS': 'Points to something nearby',
    'THUS': 'Another way to say therefore',
    'TILL': 'Until a certain time',
    'TOLD': 'Gave someone information',
    'TOOK': 'Picked up or carried away',
    'TYPE': 'A kind of thing or to write with keys',
    'UPON': 'On top of or right after',
    'USED': 'Already put to work',
    'VEIN': 'A tube that carries blood toward the heart',
    'VERY': 'A word that makes a description stronger',
    'VOTE': 'Choose by marking your choice',
    'WENT': 'Moved from one place to another',
    'WERE': 'A past form of the word be',
    'WHAT': 'A question word asking which thing',
    'WHEN': 'A question word asking what time',
    'WHOM': 'A word asking which person receives an action',
    'WIFE': 'A married woman',
    'WILL': 'A word about the future or determination',
    'WITH': 'Together or accompanied by',
    'YOUR': 'Belonging to you',
    'ABOUT': 'Concerning something or nearby',
    'ABOVE': 'Higher than something else',
    'ACUTE': 'Sharp, severe, or less than a right angle',
    'AFTER': 'Later than something else',
    'AGAIN': 'One more time',
    'AGREE': 'To have the same opinion',
    'ALIVE': 'Living, not dead',
    'ALLOW': 'To let something happen',
    'ALONE': 'By yourself',
    'ALONG': 'Moving beside or forward with',
    'AMONG': 'In the middle of a group',
    'ANGRY': 'Feeling mad',
    'APART': 'Separated from each other',
    'ASIDE': 'To one side',
    'AVOID': 'Keep away from something',
    'BEGAN': 'Started',
    'BEGIN': 'To start',
    'BEGUN': 'Already started',
    'BEING': 'Existing or living',
    'BELOW': 'Lower than something else',
    'BLACK': 'The darkest color',
    'BLAME': 'Say someone caused a problem',
    'BLOOD': 'Red liquid that moves through your body',
    'BOOTS': 'Shoes that cover the ankle or more',
    'BOUND': 'Tied, headed somewhere, or certain',
    'BREAK': 'To crack, stop, or take a rest',
    'BRING': 'Carry something to this place',
    'BROAD': 'Wide from side to side',
    'BROKE': 'Cracked or had no money',
    'BROWN': 'A color like chocolate or tree bark',
    'BRUSH': 'A tool with bristles or to sweep lightly',
    'BUILT': 'Made by putting parts together',
    'BURST': 'Break open suddenly',
    'CANAL': 'A man-made waterway',
    'CARRY': 'Hold and move something',
    'CARTS': 'Small vehicles used to carry things',
    'CAUSE': 'Something that makes another thing happen',
    'CHAIR': 'A seat for one person',
    'CHEST': 'The front part of your body below your neck',
    'CHIEF': 'The leader or most important person',
    'CHILD': 'A young person',
    'CIVIL': 'Polite or related to citizens',
    'CLASS': 'A group of students learning together',
    'CLEAR': 'Easy to see through or understand',
    'CLOCK': 'Something that tells the time',
    'CLOSE': 'Nearby or to shut something',
    'COULD': 'A word meaning was able to or might',
    'COUNT': 'Say numbers in order or find how many',
    'COURT': 'A place for law or some sports',
    'CRIED': 'Made tears or called out loudly',
    'CROSS': 'Go from one side to another',
    'CROWD': 'A large group of people together',
    'DOING': 'Working on or performing something',
    'DOUBT': 'A feeling of not being sure',
    'DRAWN': 'Made as a picture or pulled',
    'DREAM': 'A story in your mind while sleeping',
    'DRESS': 'Clothing or to put clothes on',
    'DRINK': 'A liquid you swallow',
    'DRIVE': 'Control a car or push something forward',
    'DROVE': 'Controlled a car in the past',
    'EARLY': 'Before the usual time',
    'EDGES': 'The outside borders of things',
    'EIGHT': 'The number after seven',
    'ELBOW': 'The joint in the middle of your arm',
    'ENEMY': 'Someone on the opposite side',
    'ENTER': 'Go inside',
    'EQUAL': 'The same amount or value',
    'EVENT': 'Something that happens',
    'EVERY': 'Each one in a group',
    'FAVOR': 'A kind act or something you prefer',
    'FEVER': 'A body temperature higher than normal',
    'FIELD': 'An open area of land',
    'FIFTY': 'The number 50',
    'FIGHT': 'A struggle or argument',
    'FIRST': 'Before all the others',
    'FIXED': 'Repaired or made not to move',
    'FLAME': 'The glowing part of a fire',
    'FLANK': 'The side of a person, animal, or group',
    'FLOOR': 'The surface you walk on inside',
    'FLUID': 'A liquid or something that flows',
    'FORCE': 'A push or pull',
    'FORTH': 'Forward or outward',
    'FORTY': 'The number 40',
    'FOUND': 'Discovered or located',
    'FRESH': 'New, clean, or recently made',
    'FRONT': 'The forward-facing side',
    'GIVEN': 'Handed or provided',
    'GLASS': 'A clear material used in windows',
    'GOING': 'Moving or traveling somewhere',
    'GRAND': 'Large, impressive, or one thousand',
    'GRASS': 'Green plants that cover many lawns',
    'GREAT': 'Very good or very large',
    'GREEN': 'A color like leaves and grass',
    'GROUP': 'A number of things together',
    'GROWN': 'Become bigger or older',
    'HAPPY': 'Feeling glad or joyful',
    'HEARD': 'Received a sound with your ears',
    'HEART': 'The organ that pumps blood',
    'HEAVY': 'Weighing a lot',
    'HONOR': 'Respect and praise',
    'HOUSE': 'A building where people live',
    'HUMAN': 'A person',
    'BEAR': 'A large furry animal',
    'BIRD': 'An animal with feathers',
    'BOOK': 'Something you read',
    'CAKE': 'A sweet birthday treat',
    'CAMP': 'Sleep outside in a tent',
    'DUCK': 'A bird that likes water',
    'FISH': 'An animal that swims',
    'FROG': 'A green animal that hops',
    'GAME': 'Something you play',
    'GOAT': 'A farm animal',
    'KITE': 'You fly it in the wind',
    'LION': 'A big cat with a mane',
    'MOON': 'You can see it at night',
    'RAIN': 'Water that falls from clouds',
    'SHIP': 'A large boat',
    'SHOE': 'You wear it on your foot',
    'STAR': 'It twinkles in the night sky',
    'TREE': 'A tall plant with a trunk',
    'WAVE': 'Moving water at the beach',
    'WOLF': 'A wild animal related to dogs',
    'APPLE': 'A crunchy fruit',
    'BEACH': 'A sandy place by the water',
    'BREAD': 'You might use it for a sandwich',
    'CLOUD': 'A fluffy shape in the sky',
    'DANCE': 'Move your body to music',
    'EARTH': 'The planet we live on',
    'GRAPE': 'A small round fruit',
    'HORSE': 'An animal people can ride',
    'JUICE': 'A fruity drink',
    'MOUSE': 'A small animal with a long tail',
    'NIGHT': 'The time when it is dark',
    'OCEAN': 'A huge body of salt water',
    'PANDA': 'A black-and-white bear',
    'PIZZA': 'A cheesy food cut into slices',
    'PLANT': 'A living thing that grows',
    'ROBOT': 'A machine that can do tasks',
    'SHEEP': 'A farm animal with wool',
    'SMILE': 'What your face does when you are happy',
    'TRAIN': 'A vehicle that travels on tracks',
    'WHALE': 'A very large ocean animal',
    'ANIMAL': 'A living creature',
    'BANANA': 'A long yellow fruit',
    'BUBBLE': 'A round pocket of air in soapy water',
    'CASTLE': 'A large home for kings and queens',
    'COOKIE': 'A small sweet baked treat',
    'DRAGON': 'A make-believe fire-breathing creature',
    'FLOWER': 'A colorful part of a plant',
    'FOREST': 'A place with many trees',
    'GARDEN': 'A place where plants are grown',
    'KITTEN': 'A baby cat',
    'MONKEY': 'An animal that can climb and swing',
    'ORANGE': 'A fruit and a color',
    'PENCIL': 'You use it to write or draw',
    'PUPPET': 'A toy you can make move',
    'RABBIT': 'An animal with long ears',
    'ROCKET': 'A vehicle that can travel to space',
    'SCHOOL': 'A place where children learn',
    'SPIDER': 'A creature with eight legs',
    'TURTLE': 'An animal with a shell',
    'WINTER': 'The coldest season',
    'BALLOON': 'A colorful object filled with air',
    'BEDROOM': 'A room where you sleep',
    'CHICKEN': 'A farm bird',
    'DOLPHIN': 'A smart ocean animal',
    'DRAWING': 'A picture made with a pencil or crayon',
    'FIREMAN': 'A person who helps put out fires',
    'GIRAFFE': 'A very tall animal with a long neck',
    'HAMSTER': 'A small furry pet',
    'KITCHEN': 'A room where food is prepared',
    'LADYBUG': 'A small red beetle with spots',
    'LIBRARY': 'A place full of books',
    'PENGUIN': 'A black-and-white bird that cannot fly',
    'RAINBOW': 'Colors that can appear after rain',
    'SANDBOX': 'A box where kids can play with sand',
    'SNOWMAN': 'A person-shaped figure made of snow',
    'SUNSHINE': 'Bright light from the sun',
    'TRICYCLE': 'A three-wheeled ride',
    'VOLCANO': 'A mountain that can erupt',
    'PANCAKE': 'A round breakfast food cooked on a griddle',
    'POPCORN': 'A crunchy snack made from corn',
    'AIRPLANE': 'A vehicle that flies in the sky',
    'BASEBALL': 'A sport played with a bat and ball',
    'BIRTHDAY': 'The day you celebrate getting one year older',
    'DINOSAUR': 'An ancient animal that lived long ago',
    'ELEPHANT': 'A huge animal with a trunk',
    'FOOTBALL': 'A sport played with an oval ball',
    'KANGAROO': 'An animal that hops and has a pouch',
    'MOUNTAIN': 'Very high land',
    'NOTEBOOK': 'A book of blank pages for writing',
    'PLAYROOM': 'A room for toys and games',
    'SANDWICH': 'Food between slices of bread',
    'SEAHORSE': 'A tiny ocean animal shaped a bit like a horse',
    'SNOWBALL': 'A ball made of packed snow',
    'SQUIRREL': 'A furry animal that likes nuts',
    'SUNLIGHT': 'Light that comes from the sun',
    'TREASURE': 'Something valuable that might be hidden',
    'UMBRELLA': 'You hold it over your head in the rain',
    'VACATION': 'Time away from school or work',
    'RAINCOAT': 'A coat worn in wet weather',

    // Clue bank expansion — first broad pass across common 4-letter words.
    'ABLE': 'Can do something',
    'AREA': 'A place or part of a place',
    'ARMY': 'A large group of soldiers',
    'AWAY': 'Not here',
    'BABY': 'A very young child',
    'BACK': 'The part of your body behind you',
    'BALL': 'A round thing used in many games',
    'BANK': 'A place that keeps money safe',
    'BENT': 'Not straight',
    'BEST': 'Better than all the rest',
    'BILL': 'Money you owe, or a paper dollar',
    'BLUE': 'The color of a clear sky',
    'BOAT': 'A vehicle that travels on water',
    'BODY': 'All of a person or animal',
    'BONE': 'A hard part inside your body',
    'BOTH': 'The two of them together',
    'CALL': 'Talk to someone by phone',
    'CALM': 'Peaceful and not upset',
    'CARD': 'A small piece of stiff paper',
    'CARE': 'Look after someone or something',
    'CITY': 'A large town with many people',
    'COAT': 'Warm clothing worn over your clothes',
    'COLD': 'The opposite of hot',
    'CORN': 'A yellow vegetable that grows on a cob',
    'CRAB': 'An ocean animal with claws',
    'DARK': 'With little or no light',
    'DEEP': 'Going far down',
    'DEER': 'A wild animal that may have antlers',
    'DESK': 'A table used for schoolwork or work',
    'DOOR': 'You open it to enter a room',
    'DOWN': 'The opposite of up',
    'EACH': 'Every one by itself',
    'EAST': 'The direction where the sun rises',
    'EASY': 'Not hard to do',
    'FACE': 'The front of your head',
    'FALL': 'To drop down, or a season of the year',
    'FARM': 'A place where crops or animals are raised',
    'FEET': 'You stand and walk on them',
    'FIND': 'To discover where something is',
    'FINE': 'Okay or doing well',
    'FIRE': 'Hot flames that give heat and light',
    'FIVE': 'The number after four',
    'FLAG': 'A piece of cloth that can represent a place',
    'FOOT': 'The body part at the end of your leg',
    'FOUR': 'The number after three',
    'FREE': 'Not trapped or not costing money',
    'GIRL': 'A young female person',
    'GIVE': 'To hand something to someone else',
    'GLAD': 'Happy about something',
    'GOLD': 'A shiny yellow metal',
    'GOOD': 'Nice, right, or well done',
    'GRAY': 'A color between black and white',
    'HAIR': 'It grows on your head',
    'HALF': 'One of two equal parts',
    'HAND': 'The body part with fingers',
    'HARD': 'Not easy, or not soft',
    'HEAD': 'The top part of your body',
    'HEAR': 'To notice sound with your ears',
    'HELP': 'To make something easier for someone',
    'HIGH': 'Far above the ground',
    'HILL': 'Raised land smaller than a mountain',
    'HOME': 'The place where you live',
    'HOPE': 'To wish for something good to happen',
    'HOUR': 'Sixty minutes',
    'HUGE': 'Very, very big',
    'IDEA': 'A thought or plan in your mind',
    'JUMP': 'Push off the ground into the air',
    'KEEP': 'To hold onto something',
    'KIND': 'Nice and caring',
    'KING': 'A male ruler in a kingdom',
    'KNEE': 'The joint in the middle of your leg',
    'LADY': 'An adult woman',
    'LAMP': 'A light you can turn on',
    'LAND': 'Ground that is not water',
    'LAST': 'Coming after all the others',
    'LATE': 'After the expected time',
    'LEAF': 'A flat green part of a plant or tree',
    'LEFT': 'The opposite direction from right',
    'LIFE': 'The time when a living thing is alive',
    'LINE': 'A long narrow mark',
    'LIPS': 'The soft edges around your mouth',
    'LIVE': 'To be alive or make your home somewhere',
    'LONG': 'Not short',
    'LOOK': 'Use your eyes to see',
    'LOVE': 'A strong feeling of caring',
    'MAIN': 'The most important one',
    'MAKE': 'To create or build something',
    'MANY': 'A large number of things',
    'MEET': 'To come together with someone',
    'MILK': 'A white drink that comes from cows and other animals',
    'MIND': 'The part of you that thinks',
    'MISS': 'To not hit, catch, or find something',
    'MORE': 'A bigger amount',
    'MOVE': 'To change place or position',
    'NAME': 'The word people call you',
    'NEAR': 'Close by',
    'NECK': 'The body part between your head and shoulders',
    'NEED': 'Something you must have or do',
    'NEST': 'A home built by a bird',
    'NEWS': 'Information about things that happened',
    'NEXT': 'Coming right after this one',
    'NOSE': 'The part of your face used for smelling',
    'NOTE': 'A short written message',
    'OPEN': 'Not closed',
    'OVER': 'Above something',
    'PARK': 'A place outdoors for playing or relaxing',
    'PART': 'One piece of a whole thing',
    'PATH': 'A small way or trail to walk on',
    'PEAR': 'A sweet fruit with a narrow top',
    'PINK': 'A light red color',
    'PLAN': 'An idea for what you will do',
    'PLAY': 'To have fun with a game or toy',
    'POOR': 'Having very little money',
    'POST': 'A tall upright pole',
    'READ': 'To understand words on a page',
    'REST': 'To stop and relax for a while',
    'RING': 'A small circle worn on a finger',
    'ROAD': 'A way that cars travel on',
    'ROCK': 'A hard piece of stone',
    'ROOM': 'A space inside a building',
    'ROSE': 'A flower that often has thorns',
    'RULE': 'Something that tells what is allowed',
    'SEAT': 'A place to sit',
    'SEND': 'To make something go to another person or place',
    'SHOW': 'To let someone see something',
    'SIDE': 'One edge or part of something',
    'SIGN': 'A notice that gives information',
    'SIZE': 'How big or small something is',
    'SKIN': 'The outside covering of your body',
    'SNOW': 'Soft white flakes that fall in cold weather',
    'SOCK': 'Clothing worn on your foot inside a shoe',
    'SOFA': 'A soft seat for more than one person',
    'SOFT': 'Easy to press and not hard',
    'SOIL': 'Dirt where plants grow',
    'SOON': 'In a short time',
    'STEP': 'One movement of your foot while walking',
    'STOP': 'To not keep going',
    'SWIM': 'Move through water using your body',
    'TAKE': 'To pick up or carry something with you',
    'TALK': 'To speak with someone',
    'TELL': 'To give someone information with words',
    'THIN': 'Not thick',
    'TIME': 'What clocks measure',
    'TONE': 'The sound or feeling of a voice',
    'TOWN': 'A place where people live, smaller than a city',
    'TRUE': 'Correct and not made up',
    'TURN': 'To change direction',
    'VIEW': 'What you can see from a place',
    'WAIT': 'To stay until something happens',
    'WALL': 'A side of a room or building',
    'WANT': 'To wish to have or do something',
    'WEAK': 'Not very strong',
    'WEEK': 'Seven days',
    'WELL': 'In a good or healthy way',
    'WEST': 'The direction where the sun sets',
    'WIDE': 'Having lots of space from side to side',
    'WIND': 'Moving air you can feel',
    'WING': 'A body part that helps a bird fly',
    'WISH': 'To hope for something you want',
    'WOOD': 'The hard material inside a tree',
    'WORD': 'A group of letters with meaning',
    'WORK': 'A job or task you do',
    'WORM': 'A small long animal with no legs',
    'YEAR': 'Twelve months',
  };

  if (!window.ANSWER_WORDS || typeof window.ANSWER_WORDS !== 'object') {
    window.SNOWMAN_WORDS = [];
    window.SNOWMAN_WORD_SOURCE_ERROR = true;
    return;
  }

  const words = [];
  for (let length = 4; length <= 8; length++) {
    const shared = Array.isArray(window.ANSWER_WORDS[String(length)])
      ? window.ANSWER_WORDS[String(length)]
      : (Array.isArray(window.ANSWER_WORDS[length]) ? window.ANSWER_WORDS[length] : []);
    for (const rawWord of shared) {
      const word = String(rawWord).trim().toUpperCase();
      if (!/^[A-Z]+$/.test(word) || word.length !== length) continue;
      words.push({
        word,
        clue: clueOverrides[word] || 'No clue for this word yet — try a letter!'
      });
    }
  }

  window.SNOWMAN_WORDS = words;
  window.SNOWMAN_WORD_SOURCE = 'Learn to Readle reviewed answer bank';
})();
